#!/bin/bash

PRETEND=
DELETE_FLAGS=
RESTORE=
BATCH=
MSYNC_PATHS=~/.msync_paths

ARGS=$(getopt -o pdrzbf: --long pretend,delete,restore,compress,batch,file: -n msync -- "$@")

if [ $? != 0 ] ; then
  echo "Terminating..." >&2
  exit 1
fi

eval set -- "$ARGS"

while true; do
  case "$1" in
    -p | --pretend )
      PRETEND=YES
      ;;
    -d | --delete )
      DELETE_FLAGS=" --delete --delete-excluded"
      ;;
    -r | --restore)
      RESTORE=YES
      ;;
    -z | --compress )
      COMPRESS_FLAG=YES
      ;;
    -f | --file)
      shift
      MSYNC_PATHS="$1"
      ;;
    -b | --batch)
      BATCH=YES
      ;;
    --)
      shift
      break
      ;;
    *)
      break ;;
  esac

  shift
done

echo "Reading paths from $MSYNC_PATHS"

if [[ -f "$MSYNC_PATHS" && -r "$MSYNC_PATHS" ]] ; then
	. $MSYNC_PATHS
	if [[ -z "$MSYNC_SERVER" ]] ; then
		echo "Environment variable MSYNC_SERVER is not set."
		exit 1
	fi
	echo Synchronising with $MSYNC_SERVER
else
	echo "File $MSYNC_PATHS does not exist or not readable."
	exit 1
fi

# msync what?
# set SRC and TGT variables
case $1 in
  music)
    echo "Syncing music"
    SRC=/var/media/music
    TGT="sshd@${MSYNC_SERVER}:/shares/Public/Shared Music"
    ;;
  video)
    echo "Syncing video"
    SRC=/var/media/video
    TGT="sshd@${MSYNC_SERVER}:/shares/Public/Shared Videos"
    ;;
  pictures)
	echo "Syncing pictures"
	SRC=/var/media/pictures
	TGT="sshd@${MSYNC_SERVER}:/shares/Public/Shared Pictures"
	;;
  stuff)
	echo "Syncing stuff"
	SRC=/var/media/stuff
	TGT="sshd@${MSYNC_SERVER}:/shares/media/stuff"
	;;
  tmp)
	echo "Syncing tmp"
	SRC=/var/media/tmp
	TGT="sshd@${MSYNC_SERVER}:/shares/secure"
	;;
  *)
    echo "Unknown source: $1"
    exit -1
    ;;
esac

if [ -z "$RESTORE" ] ; then
  MSSRC="$SRC/"
  MSTGT="$TGT"
else
  MSSRC="$TGT/"
  MSTGT="$SRC"
fi

MSARGS="aPvs"

[ ! -z "$PRETEND" ] && MSARGS="${MSARGS}n"
[ ! -z "$COMPRESS_FLAG" ] && MSARGS="${MSARGS}z"

if [ -z "$BATCH" ] ; then
  MSARGS="${MSARGS}P"
else
  MSARGS="${MSARGS} --partial"
fi

echo "======================"
echo "Sync source: $MSSRC"
echo "Sync target: \"$MSTGT\""
echo "Arguments: \"$MSARGS\""

CMD="rsync -${MSARGS}${DELETE_FLAGS} --exclude '*.DS_Store' $MSSRC \"$MSTGT\""

echo "Issuing command: '$CMD'"
echo "======================"

rsync -$MSARGS${DELETE_FLAGS} --exclude '*.DS_Store' "$MSSRC" "$MSTGT"
