#!/bin/bash

PRETEND=
DELETE_FLAGS=
RESTORE=
BATCH=
MSYNC_PATHS=~/.msync_paths

ARGS=$(getopt -o pdrbf: --long pretend,delete,restore,batch,file: -n msync -- "$@")

if [ $? != 0 ] ; then
  echo "Terminating..." >&2
  exit 1
fi

eval set -- "$ARGS"

while true; do
  case "$1" in
    -p | --pretend )
      PRETEND=YES
      ;;
    -d | --delete )
      DELETE_FLAGS=" --delete --delete-excluded"
      ;;
    -r | --restore)
      RESTORE=YES
      ;;
	-f | --file)
	  shift
	  MSYNC_PATHS="$1"
	  ;;
	-b | --batch)
	  BATCH=YES
	  ;;
    --)
      shift
      break
      ;;
    *)
      break ;;
  esac

  shift
done

echo "Reading paths from $MSYNC_PATHS"

# msync what?
# set SRC and TGT variables
case $1 in
  music)
    echo "Syncing music"
    SRC=/var/media/music
    TGT="sshd@10.1.1.11:/shares/Public/Shared Music"
    ;;
  video)
    echo "Syncing video"
    SRC=/var/media/video
    TGT="sshd@10.1.1.11:/shares/Public/Shared Videos"
    ;;
  pictures)
	echo "Syncing pictures"
	SRC=/var/media/pictures
	TGT="sshd@10.1.1.11:/shares/Public/Shared Pictures"
	;;
  stuff)
	echo "Syncing stuff"
	SRC=/var/media/stuff
	TGT="sshd@10.1.1.11:/shares/media/stuff"
	;;
  *)
    echo "Unknown source: $1"
    exit -1
    ;;
esac

if [ -z "$RESTORE" ] ; then
  MSSRC="$SRC/"
  MSTGT="$TGT"
else
  MSSRC="$TGT/"
  MSTGT="$SRC"
fi

MSARGS="azvs"

[ ! -z "$PRETEND" ] && MSARGS="${MSARGS}n"

if [ -z "$BATCH" ] ; then
  MSARGS="${MSARGS}P"
else
  MSARGS="${MSARGS} --partial"
fi

echo "======================"
echo "Sync source: $MSSRC"
echo "Sync target: \"$MSTGT\""
echo "Arguments: \"$MSARGS\""

CMD="rsync -${MSARGS}${DELETE_FLAGS} --exclude '*.DS_Store' $MSSRC \"$MSTGT\""

echo "Issuing command: '$CMD'"
echo "======================"

rsync -$MSARGS${DELETE_FLAGS} --exclude '*.DS_Store' "$MSSRC" "$MSTGT"
